package com.aca.carfabric.engine.models;

public enum CarType {
    CROSSOVER_ECONOM, CROSSOVER_SPORT, CROSSOVER_BUSINESS,
    SEDAN_SPORT, SEDAN_BUSINESS, SEDAN_ECONOM,
    HATCHBACK_SPORT, HATCHBACK_BUSINESS, HATCHBACK_ECONOM,
    TRUCK, TRACTOR, MOTORCYCLE
}
